# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_proximityreading_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeaconReading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.IntegerField()),
                ('beacon', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
