# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20160218_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceuser',
            name='email',
            field=models.EmailField(default='', max_length=40),
        ),
    ]
