# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_beaconreading_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beaconreading',
            name='beacon',
            field=models.CharField(max_length=40),
        ),
    ]
