# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20160307_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='beaconreading',
            name='major',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beaconreading',
            name='minor',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
