# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20160307_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='beaconreading',
            name='major',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='beaconreading',
            name='minor',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='beaconreading',
            name='beacon',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='deviceuser',
            name='device',
            field=models.CharField(default='', max_length=50),
        ),
    ]
